sudo: false
language: cpp
addons:
  apt:
    packages:
    - python-serial
    - srecord
install:
- cd toolchain
- python gen.py
- cd ..
script:
- cd sketch/mjyun
- make clean
- make
- cd ../../
# http://docs.travis-ci.com/user/environment-variables/#Convenience-Variables
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash "$TRAVIS_BUILD_DIR"/tools/pr-build.sh; fi